<div class="background">
    <div class="container">
        <?php $this->insert('pages/galery'); ?>
        <?php $this->insert('pages/news'); ?>
        <?php $this->insert('pages/angebot'); ?>
        <?php $this->insert('pages/impressionen'); ?>
        <?php $this->insert('pages/oeffnungszeiten'); ?>
        <?php $this->insert('pages/kontakt'); ?>
        <?php $this->insert('pages/footer'); ?>
        <?php $this->insert('pages/layer'); ?>
    </div>
</div>