<?php
    $path = 'img/icons/Icon_';
?>
<div id="angebot" class="angebot">
    <?php foreach ($this->translate('angebot.content') as $array): ?>
        <div class="content">
            <?php foreach ($array as $text): ?>
            <div class="container" id='<?= $text ?>'>
                <div class="text">
                    <img src="<?= $this->resourceHelper($path . $text . '.svg' )?>">
                    <p class="head"><?= $text ?></p>
                    <div class="button" id="quality-btn"><?= $this->translate('angebot.button-lable')?></div>
                </div>
            </div>
            <?php endforeach ?>
        </div>
    <?php endforeach; ?>
</div>