<div id="galary" class="bilder-galary">
    <div class="slider">
        <div class="slider-content">
            <div class="wrapper">
                <div class="container" id="test">
                    <div class="picture show" id="pic-0"></div>
                    <div class="picture" id="pic-1"></div>
                    <div class="picture" id="pic-2"></div>
                    <div class="picture" id="pic-3"></div>
                    <div class="picture" id="pic-4"></div>
                </div>
            </div>
        </div>
    </div>
</div>