<?php
	if(!empty($_POST['imagecount'])) {
		$imagecount = $_POST['imagecount'];
	} else {
		$imagecount = '1';
	}

	$path = 'img/';
?>
<div class="impression-layer">
	<div class="container">
		<img  class="close" onclick="closeLayer()" src="<?= $this->resourceHelper('img/icons/Icon_schließen.svg')?>">
		<div class="wrapper">
			<div class="image-wrapper">
				<?php foreach($this->translate('impressionlayer.imagecontainer') as $array) :?>
					<div class="image-container">
						<img src="<?= $this->resourceHelper($path . $array['image'] . '.jpg')?>">
						<p><?= $array['text'] ?></p>
					</div>
				<?php endforeach; ?>
			</div>
		</div>
		<div class="left-arrow"></div>
		<div class="right-arrow"></div>
		<div class="counter"><?php $imagecount ?>/2</div>
	</div>
</div>