<?php

$this->form->setAttribute('action', '/');
$this->form->prepare();

?>

<h1>Tragen sie das datum und eine beschreibung für das ereigniss ein</h1>

<div class="formular">
    <form class="formular-berreich" method="POST">
        <div class="wrapper">
            <?php echo $this->formRow($this->form->get('name')); ?>
        </div>
        <div class="wrapper">
            <?php echo $this->formRow($this->form->get('datum')); ?>
        </div>
        <?php echo $this->formRow($this->form->get('abschicken')); ?>
    </form>
</div>