<div id="kalender" class="Kalender">
    <div class="KalenderButtonNext" id="next"></div>
    <div class="KalenderButtonLast" id="last"></div>
    <h1>Kalender</h1>
</div>
<div style="position: relative" class="wrapper">
    <div class="kalenderbackground"></div>
    <h1 class="month"></h1>
    <div class="kalenderberreich"></div>
</div>

<?php if(parse_url($this->serverUrl(true), PHP_URL_PATH) == '/kalenderberreich') : ?>
	<button class="saveBtn">Termin Eintragen</button>
<?php endif ?>


