<?php if($_POST['plant'] == 'gebundenes'): ?>
    <h1>Gebundenes</h1>
    <div class="text">
        <p>
        Sie wollen sich nicht darum bemühem viel zu gießen oder haben nicht die Zeit dazu?
        Dann können sie sich bei uns auch eines unsere vielen Gebunden Schönheiten aussuchen.
        wir verwenden dafür Zweige und Äste verschiedenster Bäumen und Pflanzen um damit etwas
        Kunstvolles zu entwerfen.
        </p>
        <p>
            Ob Kränze oder Gestecke wir haben für jeden geschmack etwas dabei.
        </p>
    </div>
<?php elseif($_POST['plant'] == 'gerbera'): ?>
    <h1>Gerbera</h1>
    <div class="text">
        <p>
        Gerbera-Arten und -Sorten sind mehrjährige, nicht winterharte krautige Pflanzen. In grundständigen Rosetten stehen die meist fiederteiligen oder einfachen Laubblätter zusammen. Die Blattränder sind einfach, gezähnt bis gesägt. Die Blätter können behaart oder unbehaart sein.
        Einzeln an langen blattlosen Stängeln stehen die körbchenförmigen Blütenstände. Die äußeren Blüten sind weiblich meist mit Staminodien, die inneren sind zwittrig oder funktional männlich. Die Kronröhre endet zweizipfelig. Die Achänen sind vier- bis zehngerippt mit einem Pappus.
        </p>
    </div>
<?php elseif($_POST['plant'] == 'zitronenbaum'): ?>
    <h1>Zitronenbaum</h1>
    <div class="text">
        <p>
        Zitronenbäume gedeihen auch in Mitteleuropa. Eine Besonderheit des Zitronenbaums ist, dass dieser ganzjährig gleichzeitig Blüten wie Früchte trägt. Von Mitte Mai bis zum ersten Frost sollte die Zitrone im Freien stehen, an einem windgeschützten Platz. Im Winter muss die Temperatur an die Lichtverhältnisse angepasst werden. Werden die Zitronenbäume hell, aber kalt gestellt, so haben die Blätter zwar noch ausreichend Licht, allerdings stellen die Wurzeln  die Aktivität beinahe vollständig ein. Dies hat zur Folge, dass der Baum die Blätter nicht mehr ausreichend versorgen kann und er wirft diese in weiterer Folge ab. Als häufige Schädlinge kommen Schildläuse vor.
        </p>
    </div>
<?php elseif($_POST['plant'] == 'sonstiges'): ?>
    <h1>Krimms-Kramms</h1>
    <div class="text">
        <p>
            Sie haben viele Pflanzen bei sich? Suchen denoch etwas was dazu passt was nicht Planzlich ist?
            Dann haben wir auch hierfür passendes in Unserem Angebot wir haben eine vielzahl an Töpfen,
            Figuren und verziehrungsmöglichkeiten.
        </p>
        <p>
            Dadurch können sie ihrem garten noch einen weitern hauch schönheit schenken.
        </p>
    </div>
<?php elseif($_POST['plant'] == 'tulpen'): ?>
    <h1>Tulpen</h1>
    <div class="text">
        <p>
        Tulpen sind bedeutende Zierpflanzen, sowohl als Gartenpflanzen wie als Schnittblumen. Über 80 % der Welt-Tulpenproduktion stammt aus den Niederlanden. Hier werden über 1200 Sorten kultiviert, jedoch nehmen die 40 häufigsten über die Hälfte der Anbauflächen ein.
        In der Heilkunde bzw. medizinischen Anwendung spielen Tulpen keine Rolle. sie sind sogar giftig für Menschen und Tiere (z.B. Pferde, Hunde und Katzen sowie für Nager). Das in den Zwiebeln und Sprossen enthaltene Tulipanin verursacht u.a. Erbrechen, Magen - und Darmbeschwerden, Bauchkrämpfe.
        </p>
    </div>
<?php elseif($_POST['plant'] == 'rosen'): ?>
    <h1>Rosen</h1>
    <div class="text">
        <p>
        Die wichtigste Nutzung der Rosen ist die Verwendung als Zierpflanze, sowohl als Gartenpflanze als auch als Schnittblume. Das Rosenöl wird in der Parfumindustrie verwendet. Das bei der Gewinnung von Rosenöl anfallende Rosenwasser wird bei der Herstellung von Marzipan und Lebkuchen verwendet.
        In der Heilkunde werden ganze Hagebutten, Hagebuttenschalen und die Hagebuttenkerne genutzt. Verwendet werden verschiedene Arten.Verwendet werden Hagebutten gegen Erkältungskrankheiten, Darmerkrankungen, Gallenleiden bei Gicht und Rheuma. Die Wirksamkeit ist in allen Fällen nicht bzw. nicht ausreichend belegt. Verwendet werden die Hagebutten besonders in Frühstücktees. Frische Hagebutten werden zu Marmeladen verarbeitet. Auch in der Aromatherapie wird der Rosenduft aufgrund seiner entspannenden Wirkung zu therapeutischen Zwecken eingesetzt. In Asien werden in der Volksmedizin auch getrocknete Blüten, Blätter und Wurzeln verwendet. Das Holz wird in der Kunsttischlerei für Drechsel- und Einlegearbeiten verwendet.
        </p>
    </div>
    <?php elseif($_POST['plant'] == 'advent'): ?>
    <h1>AdventsKränze</h1>
    <div class="text">
        <p>
        Es geht richtung Weihnachten Sie suchen AdventsKränze oder einen Christbaum?
        Dann schauen sie doch bei uns vorbei wir haben eine Vielzahl an Kränzen und Bäumen.
        Wir haben einen Speziellen ausstellungs platz an dem sie aller hand verschöhnerungen finden können.
        Ist nichts dabei was ihnen gefällt? Gerne erstellen wir auch einen Kranz ganz nach ihrem geschmack.
        Das dass weihnachtsfest etwas ganz besonderes wird.
        </p>
    </div>
<?php endif ?>


