<?php
	if(!empty($_POST)) {
		$text = $_POST['id'];
	} else {
		$text = 'fallback';
	}

	$path = 'img/icons/Icon_' . $text . '.svg';
?>
<div class="layer-angebot">
	<div class="container">
		<div class="header">
			<img src="">
			<div class="headline"><?=  $text ?></div>
			<div class="subheadline"><?=  $text ?></div>
		</div>
		<div class="left">
			<div class="textarea">
				<p><?=  $text ?></p>
				<ul class="ul-layer">
				<li>-test</li>
				<li>-test</li>
				<li>-test</li>
				<li>-test</li>
				<li>-test</li>
				<li>-test</li>
				<li>-test</li>
				</ul>
				<p><?=  $text ?></p>
			</div>
		</div>
		<div class="right">
			<img src="">
			<img src="">
			<img src="">
			<img src="">
		</div>
	</div>
</div>
