<div class="news">

    <div class="image">
        <img src="<?= $this->resourceHelper('img/02-15-03-27-AB-Kremp_March_1280.jpg') ?>">
    </div>
    <div class="news-text">
        <div class="head-text">
            <p><?= $this->translate('news.head-text')?></p>
        </div>
        <div class="col-wrapper">
            <div class="col-1">
                <p class="head"><?= $this->translate('news.first')?></p>
                <ul>
                    <li>-<?= $this->translate('news.aufzählung')?></li>
                    <li>-<?= $this->translate('news.aufzählung')?></li>
                    <li>-<?= $this->translate('news.aufzählung')?></li>
                </ul>
            </div>
            <div class="col-2">
                <p class="head"><?= $this->translate('news.second')?></p>
                <ul>
                    <li>-<?= $this->translate('news.aufzählung')?></li>
                    <li>-<?= $this->translate('news.aufzählung')?></li>
                    <li>-<?= $this->translate('news.aufzählung')?></li>
                </ul>
            </div>
        </div>
    </div>
</div>