<div class="oeffnungszeiten">
    <div class="headline">Öffnungszeiten</div>
    <div class="col-wrapper-oeffnung">
        <div class="col-1">
            <p class="head">Erstes Wochenende</p>
            <ul>
                <li>Lorem ipsum dolor sit</li>
                <li>Lorem ipsum dolor sit</li>
            </ul>
        </div>
        <div class="col-2">
            <p class="head">Zweites Wochenende</p>
            <ul>
                <li>Lorem ipsum dolor sit</li>
            </ul>
        </div>
        <div class="col-3">
            <p class="head">Zweites Wochenende</p>
            <ul>
                <li>Lorem ipsum dolor sit</li>
            </ul>
        </div>
    </div>
</div>