<div id="verkauf" class="verkauf">
    <h1>Impressionen</h1>
    <div class="contentVerkauf">
        <button class="brix-btn" id="winterhart">Winterhart</button>
        <button class="brix-btn" id="pflegeleicht">Pflegeleicht</button>
        <button class="brix-btn" id="wenig_licht">wenig Licht</button>
        <button class="brix-btn" id="wenig_wasser">wenig Wasser</button>
        <button class="brix-btn" id="alle">Alle</button>
    </div>
    <div class="wrapper">
        <div class="row">
            <div class="portfolio wenig_licht winterhart wenig_wasser" id="gebundenes">
                    <img src="<?php echo $this->basePath('../img/02-15-03-27-AB-Kremp_March_1280.jpg') ?>" alt="1337" height="100%" width="100%">
                <div class="name">
                    <h3>Gebundene Kunste</h3>
                </div>
            </div>
            <div class="portfolio wenig_wasser pflegeleicht" id="rosen">
                    <img src="<?php echo $this->basePath('../img/05-15-03-27-AB-Kremp_March_1280_04.jpg') ?>" alt="1337" height="100%" width="100%">
                <div class="name">
                    <h3>Rosen</h3>
                </div>
            </div>
            <div class="portfolio pflegeleicht" id="zitronenbaum">
                    <img src="<?php echo $this->basePath('../img/06-15-03-27-AB-Kremp_March_1280_05.jpg') ?>" alt="1337" height="100%" width="100%">
                <div class="name">
                    <h3>Zitronenbaum</h3>
                </div>
            </div>
            <div class="portfolio winterhart wenig_wasser" id="sonstiges">
                    <img src="<?php echo $this->basePath('../img/07-15-03-27-AB-Kremp_March_1280_06.jpg') ?>" alt="1337" height="100%" width="100%">
                <div class="name">
                    <h3>Krimms-Kramms</h3>
                </div>
            </div>
            <div class="portfolio wenig_licht" id="tulpen">
                    <img src="<?php echo $this->basePath('../img/10-15-03-27-AB-Kremp_March_1280_09.jpg') ?>" alt="1337" height="100%" width="100%">
                <div class="name">
                    <h3>Tulpen</h3>
                </div>
            </div>
            <div class="portfolio wenig_licht" id="gerbera">
                    <img src="<?php echo $this->basePath('../img/Gerbera-pflanzen.jpg') ?>" alt="1337" height="100%" width="100%">
                <div class="name">
                    <h3>Gerbera</h3>
                </div>
            </div>
            <div class="portfolio wenig_licht winterhart wenig_wasser pflegeleicht" id="advent">
                    <img src="<?php echo $this->basePath('../img/Adventskranz.jpg') ?>" alt="1337" height="100%" width="100%">
                <div class="name">
                    <h3>Advent</h3>
                </div>
            </div>
        </div>
    </div>
</div>